# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'whatsThat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for whatsThat

pod 'NVActivityIndicatorView'

  target 'whatsThatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'whatsThatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
